'use client'

import React, { useState } from 'react';
import { useRouter } from 'next/navigation';
import { useProblems } from '@/context/ProblemContext';
import { SupportedLanguage, Problem, Difficulty } from '@/types';
import { Plus, Trash2 } from 'lucide-react';
import { Navbar } from './Navbar';

export const AddProblemPage: React.FC = () => {
  const router = useRouter();
  const { addProblem, problems } = useProblems();
  
  const [title, setTitle] = useState('');
  const [difficulty, setDifficulty] = useState<Difficulty>('Easy');
  const [description, setDescription] = useState('');
  const [constraints, setConstraints] = useState<string[]>(['']);
  const [examples, setExamples] = useState<{input: string, output: string, explanation?: string}[]>([
    {input: '', output: ''}
  ]);
  const [starterCode, setStarterCode] = useState<Record<string, string>>({
    [SupportedLanguage.JAVASCRIPT]: '',
    [SupportedLanguage.PYTHON]: '',
    [SupportedLanguage.JAVA]: '',
    [SupportedLanguage.CPP]: ''
  });
  const [testCases, setTestCases] = useState<{input: string, output: string}[]>([{input: '', output: ''}]);
  
  // Minimal boilerplate generation
  const generateSlug = (t: string) => t.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)+/g, '');

  // Constraints handlers
  const handleAddConstraint = () => {
    setConstraints([...constraints, '']);
  };

  const handleRemoveConstraint = (index: number) => {
    setConstraints(constraints.filter((_, i) => i !== index));
  };

  const updateConstraint = (index: number, value: string) => {
    const newConstraints = [...constraints];
    newConstraints[index] = value;
    setConstraints(newConstraints);
  };

  // Examples handlers
  const handleAddExample = () => {
    setExamples([...examples, {input: '', output: ''}]);
  };

  const handleRemoveExample = (index: number) => {
    setExamples(examples.filter((_, i) => i !== index));
  };

  const updateExample = (index: number, field: 'input' | 'output' | 'explanation', value: string) => {
    const newExamples = [...examples];
    newExamples[index] = { ...newExamples[index], [field]: value };
    setExamples(newExamples);
  };

  // Test cases handlers
  const handleAddTestCase = () => {
    setTestCases([...testCases, {input: '', output: ''}]);
  };

  const handleRemoveTestCase = (index: number) => {
    setTestCases(testCases.filter((_, i) => i !== index));
  };

  const updateTestCase = (index: number, field: 'input' | 'output', value: string) => {
    const newCases = [...testCases];
    newCases[index][field] = value;
    setTestCases(newCases);
  };

  // Starter code handler
  const updateStarterCode = (language: string, code: string) => {
    setStarterCode({ ...starterCode, [language]: code });
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    // Filter out empty constraints
    const validConstraints = constraints.filter(c => c.trim() !== '');
    
    // Filter out empty examples
    const validExamples = examples.filter(ex => ex.input.trim() !== '' && ex.output.trim() !== '');
    
    // Ensure at least one constraint and one example
    if (validConstraints.length === 0) {
      alert('Please add at least one constraint');
      return;
    }
    
    if (validExamples.length === 0) {
      alert('Please add at least one example');
      return;
    }
    
    const newProblem: Problem = {
      id: '', // Will be generated by MongoDB
      slug: generateSlug(title),
      title,
      difficulty,
      description,
      examples: validExamples,
      constraints: validConstraints,
      starterCode: {
        [SupportedLanguage.JAVASCRIPT]: starterCode[SupportedLanguage.JAVASCRIPT] || '// Write your solution here...',
        [SupportedLanguage.PYTHON]: starterCode[SupportedLanguage.PYTHON] || '# Write your solution here...',
        [SupportedLanguage.JAVA]: starterCode[SupportedLanguage.JAVA] || '// Write your solution here...',
        [SupportedLanguage.CPP]: starterCode[SupportedLanguage.CPP] || '// Write your solution here...'
      },
      testCases: testCases
        .filter(tc => tc.input.trim() !== '' && tc.output.trim() !== '')
        .map((tc, i) => ({ id: i.toString(), input: tc.input, expectedOutput: tc.output }))
    };

    try {
      await addProblem(newProblem);
      router.push('/');
    } catch (error) {
      console.error('Failed to add problem:', error);
    }
  };

  return (
    <div className="min-h-screen bg-dark-bg text-gray-100 flex flex-col">
      <Navbar />
      <div className="flex-1 p-8 overflow-y-auto">
        <div className="max-w-4xl mx-auto bg-dark-layer rounded-xl shadow-2xl border border-white/10 p-8">
          <h1 className="text-2xl font-bold mb-6 text-brand-orange">Contribute a Problem</h1>
          
          <form onSubmit={handleSubmit} className="space-y-6">
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              <div className="col-span-2">
                <label className="block text-sm font-medium text-gray-400 mb-2">Problem Title</label>
                <input 
                  required
                  type="text" 
                  value={title} 
                  onChange={e => setTitle(e.target.value)}
                  className="w-full bg-dark-bg border border-white/10 rounded-lg p-3 focus:ring-1 focus:ring-brand-orange outline-none"
                  placeholder="e.g. Reverse Linked List"
                />
              </div>
              <div>
                 <label className="block text-sm font-medium text-gray-400 mb-2">Difficulty</label>
                 <select 
                   value={difficulty} 
                   onChange={e => setDifficulty(e.target.value as Difficulty)}
                   className="w-full bg-dark-bg border border-white/10 rounded-lg p-3 focus:ring-1 focus:ring-brand-orange outline-none"
                 >
                   <option value="Easy">Easy</option>
                   <option value="Medium">Medium</option>
                   <option value="Hard">Hard</option>
                 </select>
              </div>
            </div>

            <div>
               <label className="block text-sm font-medium text-gray-400 mb-2">Description (Markdown)</label>
               <textarea 
                 required
                 value={description}
                 onChange={e => setDescription(e.target.value)}
                 rows={6}
                 className="w-full bg-dark-bg border border-white/10 rounded-lg p-3 focus:ring-1 focus:ring-brand-orange outline-none font-mono text-sm"
                 placeholder="Describe the problem statement, inputs, and outputs..."
               />
            </div>

            {/* Constraints Section */}
            <div>
              <div className="flex items-center justify-between mb-2">
                 <label className="block text-sm font-medium text-gray-400">Constraints</label>
                 <button 
                   type="button" 
                   onClick={handleAddConstraint}
                   className="text-brand-orange text-sm flex items-center hover:text-white transition-colors"
                 >
                   <Plus size={16} className="mr-1" /> Add Constraint
                 </button>
              </div>
              
              <div className="space-y-2">
                 {constraints.map((constraint, index) => (
                   <div key={index} className="flex gap-2 items-center">
                     <input 
                       type="text" 
                       value={constraint}
                       onChange={e => updateConstraint(index, e.target.value)}
                       placeholder="e.g. 1 <= nums.length <= 10^4"
                       className="flex-1 bg-dark-bg border border-white/10 rounded p-2 text-sm"
                     />
                     {constraints.length > 1 && (
                       <button 
                         type="button" 
                         onClick={() => handleRemoveConstraint(index)}
                         className="p-2 text-red-500 hover:bg-red-500/10 rounded"
                       >
                         <Trash2 size={16} />
                       </button>
                     )}
                   </div>
                 ))}
              </div>
            </div>

            {/* Examples Section */}
            <div>
              <div className="flex items-center justify-between mb-2">
                 <label className="block text-sm font-medium text-gray-400">Examples</label>
                 <button 
                   type="button" 
                   onClick={handleAddExample}
                   className="text-brand-orange text-sm flex items-center hover:text-white transition-colors"
                 >
                   <Plus size={16} className="mr-1" /> Add Example
                 </button>
              </div>
              
              <div className="space-y-4">
                 {examples.map((example, index) => (
                   <div key={index} className="bg-white/5 p-4 rounded-lg space-y-2">
                     <div className="flex items-center justify-between mb-2">
                       <span className="text-xs font-medium text-gray-400">Example {index + 1}</span>
                       {examples.length > 1 && (
                         <button 
                           type="button" 
                           onClick={() => handleRemoveExample(index)}
                           className="p-1 text-red-500 hover:bg-red-500/10 rounded"
                         >
                           <Trash2 size={14} />
                         </button>
                       )}
                     </div>
                     <input 
                       type="text" 
                       value={example.input}
                       onChange={e => updateExample(index, 'input', e.target.value)}
                       placeholder="Input (e.g. nums = [2,7,11,15], target = 9)"
                       className="w-full bg-dark-bg border border-white/10 rounded p-2 text-sm font-mono"
                     />
                     <input 
                       type="text" 
                       value={example.output}
                       onChange={e => updateExample(index, 'output', e.target.value)}
                       placeholder="Output (e.g. [0,1])"
                       className="w-full bg-dark-bg border border-white/10 rounded p-2 text-sm font-mono"
                     />
                     <input 
                       type="text" 
                       value={example.explanation || ''}
                       onChange={e => updateExample(index, 'explanation', e.target.value)}
                       placeholder="Explanation (optional)"
                       className="w-full bg-dark-bg border border-white/10 rounded p-2 text-sm"
                     />
                   </div>
                 ))}
              </div>
            </div>

            {/* Starter Code Section */}
            <div>
              <label className="block text-sm font-medium text-gray-400 mb-2">Starter Code</label>
              <div className="space-y-4">
                {Object.values(SupportedLanguage).map(lang => (
                  <div key={lang} className="bg-white/5 p-4 rounded-lg">
                    <label className="block text-xs font-medium text-gray-400 mb-2 capitalize">
                      {lang === 'cpp' ? 'C++' : lang.charAt(0).toUpperCase() + lang.slice(1)}
                    </label>
                    <textarea
                      value={starterCode[lang] || ''}
                      onChange={e => updateStarterCode(lang, e.target.value)}
                      rows={8}
                      className="w-full bg-dark-bg border border-white/10 rounded p-3 font-mono text-sm focus:ring-1 focus:ring-brand-orange outline-none"
                      placeholder={`// Write starter code for ${lang}...`}
                    />
                  </div>
                ))}
              </div>
            </div>

            {/* Test Cases Section */}
            <div>
              <div className="flex items-center justify-between mb-2">
                 <label className="block text-sm font-medium text-gray-400">Test Cases</label>
                 <button 
                   type="button" 
                   onClick={handleAddTestCase}
                   className="text-brand-orange text-sm flex items-center hover:text-white transition-colors"
                 >
                   <Plus size={16} className="mr-1" /> Add Case
                 </button>
              </div>
              
              <div className="space-y-4">
                 {testCases.map((tc, index) => (
                   <div key={index} className="flex gap-4 items-start bg-white/5 p-4 rounded-lg">
                    <div className="flex-1 space-y-2">
                       <input 
                         required
                         type="text" 
                         value={tc.input}
                         onChange={e => updateTestCase(index, 'input', e.target.value)}
                         placeholder="Input (e.g. nums = [1,2], target = 3)"
                         className="w-full bg-dark-bg border border-white/10 rounded p-2 text-sm font-mono"
                       />
                       <input 
                         required
                         type="text" 
                         value={tc.output}
                         onChange={e => updateTestCase(index, 'output', e.target.value)}
                         placeholder="Expected Output (e.g. [0,1])"
                         className="w-full bg-dark-bg border border-white/10 rounded p-2 text-sm font-mono"
                       />
                    </div>
                    {testCases.length > 1 && (
                      <button 
                        type="button" 
                        onClick={() => handleRemoveTestCase(index)}
                        className="p-2 text-red-500 hover:bg-red-500/10 rounded"
                      >
                        <Trash2 size={16} />
                      </button>
                    )}
                 </div>
                 ))}
              </div>
            </div>

            <div className="pt-4 border-t border-white/10 flex justify-end">
               <button 
                 type="submit" 
                 className="bg-brand-orange hover:bg-brand-darkOrange text-white font-bold py-2 px-6 rounded-lg transition-colors shadow-lg shadow-brand-orange/20"
               >
                 Create Problem
               </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  );
};
